SIM ?= verilator
TOPLEVEL_LANG ?= verilog
COCOTB_TEST_MODULES ?= main
MODULE ?= $(COCOTB_TEST_MODULES)
EXTRA_ARGS += --trace --trace-fst --trace-structs
ifeq ($(SIM),verilator)
WAVE_FILE ?= dump.fst
SIM_ARGS += --trace-file $(WAVE_FILE)
endif
include $(shell cocotb-config --makefiles)/Makefile.sim
