SIM ?= verilator
TOPLEVEL_LANG ?= verilog
MODULE = main
export PYTHONPATH := $(realpath ..):$(PYTHONPATH)
EXTRA_ARGS += --trace --trace-fst --trace-structs
include $(shell cocotb-config --makefiles)/Makefile.sim
